name: Notify on Open Issues with Specific Labels

on:
  issues:
    types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event.issue.state == 'open' && contains(fromJson('["help wanted", "external"]'), github.event.label.name)
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Issue to work: Expensify issue #${{ github.event.issue.number }} Labeled with '${{ github.event.label.name }}'"
          body: |
            An expensify open issue has been labeled with '${{ github.event.label.name }}'.
            Issue Title: ${{ github.event.issue.title }}
            Issue URL: ${{ github.event.issue.html_url }}
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}
